# Generated by Django 4.1.7 on 2023-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
